package pojo;
// Generated Apr 16, 2016 4:39:01 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BenhNhan generated by hbm2java
 */
public class BenhNhan  implements java.io.Serializable {


     private String hoten;
     private String gioitinh;
     private String namsinh;
     private String diachi;
     private Date ngaykham;
     private Set phieuKhamBenhs = new HashSet(0);

    public BenhNhan() {
    }

	
    public BenhNhan(String hoten) {
        this.hoten = hoten;
    }
    public BenhNhan(String hoten, String gioitinh, String namsinh, String diachi, Date ngaykham) {
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.namsinh = namsinh;
       this.diachi = diachi;
       this.ngaykham = ngaykham;
    }
    public BenhNhan(String hoten, String gioitinh, String namsinh, String diachi, Date ngaykham, Set phieuKhamBenhs) {
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.namsinh = namsinh;
       this.diachi = diachi;
       this.ngaykham = ngaykham;
       this.phieuKhamBenhs = phieuKhamBenhs;
    }

    public BenhNhan(String hoten, Date ngaykham) {
        this.hoten = hoten;
        this.ngaykham = ngaykham;
    }
   
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getNamsinh() {
        return this.namsinh;
    }
    
    public void setNamsinh(String namsinh) {
        this.namsinh = namsinh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public Date getNgaykham() {
        return this.ngaykham;
    }
    
    public void setNgaykham(Date ngaykham) {
        this.ngaykham = ngaykham;
    }
    public Set getPhieuKhamBenhs() {
        return this.phieuKhamBenhs;
    }
    
    public void setPhieuKhamBenhs(Set phieuKhamBenhs) {
        this.phieuKhamBenhs = phieuKhamBenhs;
    }




}


