package pojo;
// Generated Apr 16, 2016 4:39:01 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * DonThuoc generated by hbm2java
 */
public class DonThuoc  implements java.io.Serializable {


     private int stt;
     private PhieuKhamBenh phieuKhamBenh;
     private String thuoc;
     private String dv;
     private int soluong;
     private int cachdung;

    public DonThuoc() {
    }

	
    public DonThuoc(int stt) {
        this.stt = stt;
    }
    public DonThuoc(PhieuKhamBenh phieuKhamBenh, String thuoc, String dv, int soluong, int cachdung) {
       this.phieuKhamBenh = phieuKhamBenh;
       this.thuoc = thuoc;
       this.dv = dv;
       this.soluong = soluong;
       this.cachdung = cachdung;
    }
    public DonThuoc(int stt, PhieuKhamBenh phieuKhamBenh, String thuoc, String dv, int soluong, int cachdung) {
       this.stt = stt;
       this.phieuKhamBenh = phieuKhamBenh;
       this.thuoc = thuoc;
       this.dv = dv;
       this.soluong = soluong;
       this.cachdung = cachdung;
    }
   
    public int getStt() {
        return this.stt;
    }
    
    public void setStt(int stt) {
        this.stt = stt;
    }
    public PhieuKhamBenh getPhieuKhamBenh() {
        return this.phieuKhamBenh;
    }
    
    public void setPhieuKhamBenh(PhieuKhamBenh phieuKhamBenh) {
        this.phieuKhamBenh = phieuKhamBenh;
    }
    public String getThuoc() {
        return this.thuoc;
    }
    
    public void setThuoc(String thuoc) {
        this.thuoc = thuoc;
    }
    public String getDv() {
        return this.dv;
    }
    
    public void setDv(String dv) {
        this.dv = dv;
    }
    public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }
    public int getCachdung() {
        return this.cachdung;
    }
    
    public void setCachdung(int cachdung) {
        this.cachdung = cachdung;
    }




}


