package pojo;
// Generated Apr 16, 2016 4:39:01 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PhieuKhamBenh generated by hbm2java
 */
public class PhieuKhamBenh  implements java.io.Serializable {
     private int maphieu;
     private BenhNhan benhNhan;
     private Date ngaykham;
     private String trieuchung;
     private String loaibenh;
     private Set donThuocs = new HashSet(0);

    public PhieuKhamBenh() {
    }

	
    public PhieuKhamBenh(int maphieu) {
        this.maphieu = maphieu;
    }
    public PhieuKhamBenh(BenhNhan benhNhan, Date ngaykham, String trieuchung, String loaibenh) {
       this.benhNhan = benhNhan;
       this.ngaykham = ngaykham;
       this.trieuchung = trieuchung;
       this.loaibenh = loaibenh;
    }
    public PhieuKhamBenh(int maphieu, BenhNhan benhNhan, Date ngaykham, String trieuchung, String loaibenh, Set donThuocs) {
       this.maphieu = maphieu;
       this.benhNhan = benhNhan;
       this.ngaykham = ngaykham;
       this.trieuchung = trieuchung;
       this.loaibenh = loaibenh;
       this.donThuocs = donThuocs;
    }
   
    public int getMaphieu() {
        return this.maphieu;
    }
    
    public void setMaphieu(int maphieu) {
        this.maphieu = maphieu;
    }
    public BenhNhan getBenhNhan() {
        return this.benhNhan;
    }
    
    public void setBenhNhan(BenhNhan benhNhan) {
        this.benhNhan = benhNhan;
    }
    public Date getNgaykham() {
        return this.ngaykham;
    }
    
    public void setNgaykham(Date ngaykham) {
        this.ngaykham = ngaykham;
    }
    public String getTrieuchung() {
        return this.trieuchung;
    }
    
    public void setTrieuchung(String trieuchung) {
        this.trieuchung = trieuchung;
    }
    public String getLoaibenh() {
        return this.loaibenh;
    }
    
    public void setLoaibenh(String loaibenh) {
        this.loaibenh = loaibenh;
    }
    public Set getDonThuocs() {
        return this.donThuocs;
    }
    
    public void setDonThuocs(Set donThuocs) {
        this.donThuocs = donThuocs;
    }




}


