/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyphongmachtu;
import java.util.*;
import pojo.*;
import dao.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Minh Nhi
 */
public class DSKhamBenh extends javax.swing.JFrame {
    /**
     * Creates new form DSKhamBenh
     */
    public DSKhamBenh() {
        initComponents();
        showData();
        //set ngay hien tai
        Date today = new Date(System.currentTimeMillis());
        jDateNgayKham.setDate(today);
    }
//    private void LoadData(){
//        dtm = new DefaultTableModel();
//        dtm.addColumn("Ho ten");
//        dtm.addColumn("Gioi tinh");
//        dtm.addColumn("Nam sinh");
//        dtm.addColumn("Dia chi");
//        //dtm.addColumn("Ngay kham");
//        //dau ds benh nhan theo ngay kham vao table
//        Date today = new Date(System.currentTimeMillis());
//        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
//        String temp = format.format(today);
//        for (BenhNhan a : this.bn.findAll()){
//            if (a.getNgaykham().toString().equals(temp))
//                dtm.addRow(new Object[]{a.getHoten(), a.getGioitinh(), a.getNamsinh(), a.getDiachi()});
//            }
//        this.jTableDSKhamBenh.setModel(dtm);
//    }
    public void showData(){
        //tao ten cot
        Vector cols = new Vector();
        cols.addElement("Họ tên");
        cols.addElement("Giới tính");
        cols.addElement("Năm sinh");
        cols.addElement("Địa chỉ");
        //tao vector du lieu
        Vector data = new Vector();
        Date today = new Date(System.currentTimeMillis());
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String temp = format.format(today);
        BenhNhanDAO bn = new BenhNhanDAO();
        List<BenhNhan> ds = bn.laydanhsach();
        for (int i = 0; i < ds.size(); i++){
            BenhNhan a = ds.get(i);
            if (a.getNgaykham().toString().equals(temp)){
                Vector benhnhan = new Vector();
                benhnhan.addElement(a.getHoten());
                benhnhan.addElement(a.getGioitinh());
                benhnhan.addElement(a.getNamsinh());
                benhnhan.addElement(a.getDiachi());
                data.add(benhnhan);
            }
        }
        jTableDSKhamBenh.setModel(new DefaultTableModel(data, cols));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDateNgayKham = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDSKhamBenh = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnLapPhieuKhamBenh = new javax.swing.JButton();
        btnCapNhatThongTin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSTT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboGioitinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNamsinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH KHÁM BỆNH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setText("Ngày khám:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateNgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableDSKhamBenh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDSKhamBenh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDSKhamBenhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDSKhamBenh);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setLayout(new java.awt.GridLayout(1, 3));

        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
        });
        jPanel4.add(btnThem);

        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });
        jPanel4.add(btnXoa);

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        btnLapPhieuKhamBenh.setText("Lập phiếu khám bệnh");
        btnLapPhieuKhamBenh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLapPhieuKhamBenhMouseClicked(evt);
            }
        });
        jPanel5.add(btnLapPhieuKhamBenh);

        btnCapNhatThongTin.setText("Cập nhật thông tin bệnh nhân");
        btnCapNhatThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapNhatThongTinMouseClicked(evt);
            }
        });
        jPanel5.add(btnCapNhatThongTin);

        jButton1.setText("Lịch sử khám");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel6.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setText("STT:");
        jPanel6.add(jLabel3);
        jPanel6.add(txtSTT);

        jLabel4.setText("Họ tên:");
        jPanel6.add(jLabel4);
        jPanel6.add(txtHoten);

        jLabel5.setText("Giới tính:");
        jPanel6.add(jLabel5);

        cboGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jPanel6.add(cboGioitinh);

        jLabel6.setText("Năm sinh:");
        jPanel6.add(jLabel6);
        jPanel6.add(txtNamsinh);

        jLabel7.setText("Địa chỉ:");
        jPanel6.add(jLabel7);
        jPanel6.add(txtDiachi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        // TODO add your handling code here:
        //them benh nhan vao
        BenhNhan a = new BenhNhan();
        a.setHoten(txtHoten.getText());
        a.setGioitinh(cboGioitinh.getSelectedItem().toString());
        a.setNamsinh(txtNamsinh.getText());
        a.setDiachi(txtDiachi.getText());
        a.setNgaykham(jDateNgayKham.getDate());
        BenhNhanDAO bn = new BenhNhanDAO();
        bn.themBenhNhan(a);
        //cap nhat lai danh sach
        showData();
    }//GEN-LAST:event_btnThemMouseClicked

    private void jTableDSKhamBenhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDSKhamBenhMouseClicked
        // TODO add your handling code here:
        int row = jTableDSKhamBenh.getSelectedRow();
        if (row != -1){
            txtHoten.setText(jTableDSKhamBenh.getValueAt(row, 0).toString());
            cboGioitinh.setSelectedItem(jTableDSKhamBenh.getValueAt(row, 1).toString());
            txtNamsinh.setText(jTableDSKhamBenh.getValueAt(row, 2).toString());
            txtDiachi.setText(jTableDSKhamBenh.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_jTableDSKhamBenhMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        //lay gia tri
        String hoten = txtHoten.getText();
        String gioitinh = cboGioitinh.getSelectedItem().toString();
        String namsinh = txtNamsinh.getText();
        String diachi = txtDiachi.getText();
        Date ngaykham = jDateNgayKham.getDate();
        //tao doi tuong benh nhan
        BenhNhan benhnhan = new BenhNhan(hoten, gioitinh, namsinh, diachi, ngaykham);
        //xoa benh nhan do
        BenhNhanDAO bn = new BenhNhanDAO();
        bn.xoa(benhnhan);
        //cap nhat lai danh sach
        showData();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnCapNhatThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapNhatThongTinMouseClicked
        // TODO add your handling code here:
        //lay gia tri
        String hoten = txtHoten.getText();
        String gioitinh = cboGioitinh.getSelectedItem().toString();
        String namsinh = txtNamsinh.getText();
        String diachi = txtDiachi.getText();
        Date ngaykham = jDateNgayKham.getDate();
        //tao doi tuong benh nhan
        BenhNhan benhnhan = new BenhNhan(hoten, gioitinh, namsinh, diachi, ngaykham);
        //xoa benh nhan do
        BenhNhanDAO bn = new BenhNhanDAO();
        bn.capnhat(benhnhan);
        //cap nhat lai danh sach
        showData();
    }//GEN-LAST:event_btnCapNhatThongTinMouseClicked

    private void btnLapPhieuKhamBenhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapPhieuKhamBenhMouseClicked
        // TODO add your handling code here:
        LapPhieuKhamBenh lapphieu = new LapPhieuKhamBenh(txtHoten.getText(), jDateNgayKham.getDate());
        lapphieu.setVisible(true);
    }//GEN-LAST:event_btnLapPhieuKhamBenhMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LichSuKham ls = new LichSuKham(txtHoten.getText());
        ls.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSKhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSKhamBenh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatThongTin;
    private javax.swing.JButton btnLapPhieuKhamBenh;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboGioitinh;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateNgayKham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDSKhamBenh;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtNamsinh;
    private javax.swing.JTextField txtSTT;
    // End of variables declaration//GEN-END:variables
}
